version: '3.8'

services:
  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend
    environment:
      - HOSTNAME=discovery-service
    restart: unless-stopped

  pharmacy-service:
    container_name: pharmacy-service
    image: pharmacy-service
    build:
      context: ./pharmacy-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
#      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_HOST=mongo
      - EUREKA_URI=http://discovery-service:8761/eureka/
      - HOSTNAME=pharmacy-service
    depends_on:
      - discovery-service
      - mongo
      - gateway-api-service
    restart: unless-stopped

  medicine-service:
    container_name: medicine-service
    image: medicine-service
    build:
      context: ./medicine-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - backend
    environment:
#      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URI=jdbc:mysql://mysql:3306/med?createDatabaseIfNotExist=true
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=rootpassword
      - EUREKA_URI=http://discovery-service:8761/eureka/
      - PHARMACY_SERVICE_URI=http://pharmacy-service:8080/pharmacy
      - HOSTNAME=medicine-service
    depends_on:
      - discovery-service
      - gateway-api-service
      - mysql
      - pharmacy-service
    restart: unless-stopped

  gateway-api-service:
    container_name: gateway-api-service
    image: gateway-api-service
    build:
      context: ./gateway-api-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - backend
    environment:
#      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URI=http://discovery-service:8761/eureka/
      - HOSTNAME=gateway-api-service
#      - PHARMACY_SERVICE_URI=http://pharmacy-service:8080
#      - MEDICINE_SERVICE_URI=http://medicine-service:9090
    depends_on:
      - discovery-service
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: med
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

networks:
  backend:

volumes:
  mongo-data:
  mysql-data:
